const schema = {
  EventWork: {
    name: "EventWork",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  InstitutionInstitution: {
    name: "InstitutionInstitution",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  InstitutionPlace: {
    name: "InstitutionPlace",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  InstitutionWork: {
    name: "InstitutionWork",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PersonEvent: {
    name: "PersonEvent",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PersonInstitution: {
    name: "PersonInstitution",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PersonPerson: {
    name: "PersonPerson",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PersonPlace: {
    name: "PersonPlace",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PersonWork: {
    name: "PersonWork",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PlaceEvent: {
    name: "PlaceEvent",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PlacePlace: {
    name: "PlacePlace",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  PlaceWork: {
    name: "PlaceWork",
    enable_nested_fields: true,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "source",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "source_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "target",
        index: true,
        optional: false,
        facet: false,
        type: "object",
      },
      {
        name: "target_kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "relation_type",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  Event: {
    name: "Event",
    enable_nested_fields: false,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  Institution: {
    name: "Institution",
    enable_nested_fields: false,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
  Person: {
    name: "Person",
    enable_nested_fields: false,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "first_name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "fullname",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
    ],
  },
  Place: {
    name: "Place",
    enable_nested_fields: false,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
      {
        name: "lat",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "long",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
    ],
  },
  Work: {
    name: "Work",
    enable_nested_fields: false,
    fields: [
      {
        name: "object_id",
        index: true,
        optional: false,
        facet: false,
        type: "int64",
      },
      {
        name: "name",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end_date",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "start",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "end",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "model",
        index: true,
        optional: false,
        facet: false,
        type: "string",
      },
      {
        name: "kind",
        index: true,
        optional: false,
        facet: true,
        type: "string",
      },
    ],
  },
};
